# Generated by Django 5.0.1 on 2024-01-21 00:46

import django.db.models.deletion
import apps.events.models.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('twitter', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Workshops', 'Workshops'), ('Talks', 'Talks')], default=apps.events.models.constants.EventCategory['WORKSHOPS'], max_length=50)),
                ('for_community', models.CharField(choices=[('Django Cameroon', 'Django Cameroon'), ('Django Girls Cameroon', 'Django Girls Cameroon')], default=apps.events.models.constants.Community['DJANGO_CAMEROON'], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Online', 'Online'), ('In-person', 'In-person'), ('Hybrid', 'Hybrid')], default=apps.events.models.constants.EventType['IN_PERSON'], max_length=50)),
                ('tags', models.ManyToManyField(related_name='events', to='events.eventtag')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.speaker')),
            ],
        ),
    ]
