# Generated by Django 5.0.1 on 2024-02-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_reservation_email_event_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default='87417fc6-f71b-4dc7-ad04-284b549ff8db', editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='id',
            field=models.UUIDField(default='5ca0edcf-0876-4be4-a9f7-646bf239b814', editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='id',
            field=models.UUIDField(default='b7492017-c601-42cb-a606-06d545c7df54', editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
