# Generated by Django 5.0.1 on 2026-01-13 14:15

import django.db.models.deletion
import utils.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendanceStats',
            fields=[
                ('id', models.UUIDField(default=utils.main.generate_uuid, editable=False, help_text='Unique identifier for this object', primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_registered', models.IntegerField(default=0, help_text='Total number of registrations', verbose_name='Total Registered')),
                ('total_attended', models.IntegerField(default=0, help_text='Total number of attendees who showed up', verbose_name='Total Attended')),
                ('total_cancelled', models.IntegerField(default=0, help_text='Total number of cancelled registrations', verbose_name='Total Cancelled')),
                ('total_no_show', models.IntegerField(default=0, help_text='Total number of no-shows', verbose_name='Total No Show')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to='events.event', verbose_name='Event')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Attendance Stats',
                'verbose_name_plural': 'Event Attendance Stats',
                'db_table': 'event_attendance_stats',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=utils.main.generate_uuid, editable=False, help_text='Unique identifier for this object', primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_code', models.CharField(help_text='Unique registration code for check-in', max_length=20, unique=True, verbose_name='Registration Code')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='registered', help_text='Registration status', max_length=20, verbose_name='Status')),
                ('checked_in', models.BooleanField(default=False, help_text='Whether the user has checked in', verbose_name='Checked In')),
                ('check_in_time', models.DateTimeField(blank=True, help_text='Time when user checked in', null=True, verbose_name='Check-in Time')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether a reminder has been sent', verbose_name='Reminder Sent')),
                ('confirmation_sent', models.BooleanField(default=False, help_text='Whether a confirmation email has been sent', verbose_name='Confirmation Sent')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requirements', verbose_name='Notes')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(help_text='The event being registered for', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Event')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user registering for the event', on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'db_table': 'event_registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='event_regis_event_i_a22351_idx'), models.Index(fields=['user', '-created_at'], name='event_regis_user_id_cf7b33_idx'), models.Index(fields=['registration_code'], name='event_regis_registr_f5633e_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
