# Generated by Django 5.0.1 on 2024-08-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('title', 'time', 'location')},
        ),
    ]
