# Generated by Django 5.0.1 on 2024-08-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_speaker_slug_alter_event_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('title', 'date', 'location')},
        ),
    ]
