# Generated by Django 5.0.1 on 2026-01-14 12:14

import django.db.models.deletion
import utils.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventattendancestats_eventregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=utils.main.generate_uuid, editable=False, help_text='Unique identifier for this object', primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('github_link', models.URLField(blank=True, help_text='Link to the GitHub repository', null=True, verbose_name='GitHub Link')),
                ('demo_link', models.URLField(blank=True, help_text='Link to live demo', null=True, verbose_name='Demo Link')),
                ('thumbnail', models.URLField(blank=True, help_text='Project thumbnail image URL', null=True, verbose_name='Thumbnail')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
