# Generated by Django 5.0.1 on 2024-02-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_created_at_event_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='linkedin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='twitter',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
