# Generated by Django 5.0.1 on 2024-08-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_time_event_date_alter_event_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='The thumbnail of the event', null=True, verbose_name='Event thumbnail'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='The date of the event', verbose_name='Event date'),
        ),
    ]
