# Generated by Django 5.0.1 on 2024-02-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_reservation_full_name_alter_basemodel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='sex',
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default='994586af-a2c1-4460-a3b1-f8767f18b2d1', editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='id',
            field=models.UUIDField(default='6f7dbf4e-e7f5-4b2c-a41b-27be767eb3d0', editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='id',
            field=models.UUIDField(default='11c4b4b9-f412-4ed4-a3f0-8c9cca301685', editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
