# Generated by Django 5.0.1 on 2026-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured project (max 3 featured projects)', verbose_name='Featured'),
        ),
    ]
