# Generated by Django 5.0.1 on 2026-07-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_project_is_featured'),
        ('users', '0005_delete_usersocialaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakersocialmedia',
            name='platform',
            field=models.CharField(choices=[('Twitter (X)', 'Twitter (X)'), ('LinkedIn', 'LinkedIn'), ('GitHub', 'GitHub'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('YouTube', 'YouTube'), ('TikTok', 'TikTok'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram')], help_text='Social media platform', max_length=50, verbose_name='Social Media Platform'),
        ),
        migrations.RemoveField(
            model_name='speakersocialmedia',
            name='handle',
        ),
        migrations.AddField(
            model_name='speakersocialmedia',
            name='profile_link',
            field=models.CharField(default='https://example.com', help_text='Social media profile link', max_length=100, verbose_name='Profile Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.URLField(blank=True, help_text="Speaker's photo", verbose_name='Photo URL'),
        ),
        migrations.AlterField(
            model_name='speakersocialmedia',
            name='active',
            field=models.BooleanField(default=True, help_text='Is the social media platform active?', verbose_name='Is Active'),
        ),
        migrations.DeleteModel(
            name='AvailableSocialMedia',
        ),
    ]
