# Generated by Django 5.0.1 on 2026-07-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_speakersocialmedia_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtag',
            name='color',
        ),
    ]
