# Generated by Django 5.0.1 on 2026-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventtag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.URLField(blank=True, help_text="Speaker's photo", null=True, verbose_name='Photo URL'),
        ),
    ]
