# Generated by Django 5.0.1 on 2026-07-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_speaker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The location of the event (not required for online events)', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventvenue', verbose_name='Event location'),
        ),
    ]
