# Generated by Django 5.0.1 on 2026-07-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
    ]
