# Generated by Django 5.0.1 on 2026-08-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_registration_link',
            field=models.URLField(blank=True, help_text='The link for external event registration', null=True, verbose_name='External registration link'),
        ),
    ]
