# Generated by Django 5.0.1 on 2026-08-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_external_registration_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, help_text='The speakers at the event', related_name='events', to='events.speaker', verbose_name='Event speakers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, help_text='The tags for the event', related_name='events', to='events.eventtag', verbose_name='Event tags'),
        ),
    ]
