repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.3.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
        args:
          - --types=change,ci,docs,feat,fix,refactor,remove,revert,fox
          - --scopes=bt,wifi,ethernet
          - --subject-min-length=10
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: flake8 (python)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
