# Generated by Django 5.0.1 on 2026-07-04 16:36

import apps.subs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.CharField(default=apps.subs.models.generate_verification_token, max_length=255, unique=True),
        ),
    ]
