# Generated by Django 5.0.1 on 2026-07-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_subscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionverificationtoken',
            options={'verbose_name': 'Subscription Verification Token', 'verbose_name_plural': 'Subscription Verification Tokens'},
        ),
    ]
