# Generated by Django 5.0.1 on 2026-03-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(default=None, help_text='The tags for the blog', related_name='blogs', to='blog.blogtag', verbose_name='Blog tags'),
        ),
    ]
