# Generated by Django 5.0.1 on 2026-01-13 14:15

import django.db.models.deletion
import utils.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS notifications (E.164 format, e.g., +237XXXXXXXXX)', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=utils.main.generate_uuid, editable=False, help_text='Unique identifier for this object', primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the login', verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=50, verbose_name='Device Type')),
                ('browser', models.CharField(blank=True, help_text='Browser name and version', max_length=100, verbose_name='Browser')),
                ('os', models.CharField(blank=True, help_text='Operating system name and version', max_length=100, verbose_name='Operating System')),
                ('country', models.CharField(blank=True, help_text='Country from IP geolocation', max_length=100, verbose_name='Country')),
                ('city', models.CharField(blank=True, help_text='City from IP geolocation', max_length=100, verbose_name='City')),
                ('is_new_location', models.BooleanField(default=False, help_text='Whether this is a login from a new location', verbose_name='New Location')),
                ('login_successful', models.BooleanField(default=True, help_text='Whether the login was successful', verbose_name='Login Successful')),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether a notification was sent for this login', verbose_name='Notification Sent')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who logged in', on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'db_table': 'login_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='login_histo_user_id_9416b0_idx'), models.Index(fields=['ip_address'], name='login_histo_ip_addr_3ce48d_idx'), models.Index(fields=['is_new_location'], name='login_histo_is_new__b46861_idx')],
            },
        ),
    ]
