# Generated by Django 5.0.1 on 2026-01-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography or description of the user', null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False, help_text='Designates whether the user is an event organizer', verbose_name='Is Organizer'),
        ),
    ]
