# Generated by Django 5.0.1 on 2026-07-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bio_user_is_organizer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocialAccount',
        ),
    ]
